### ISSUE TITLE
Stat Tracking

### ISSUE THREAD

**Issue by SnakeJ419** [Wylx-Bot/Wylx#83]
- [x] Track total number of commands wylx has processed
- [x] Track average time to run a command
- [x] average time to process non-command message over last 100 messages
